# Generated by Django 4.2.9 on 2024-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="date_payment",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
    ]
